// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admin.sql

package storage

import (
	"context"
)

const userIsPrivileged = `-- name: UserIsPrivileged :one
SELECT privileged FROM users WHERE login = $1
`

func (q *Queries) UserIsPrivileged(ctx context.Context, db DBTX, login string) (bool, error) {
	row := db.QueryRow(ctx, userIsPrivileged, login)
	var privileged bool
	err := row.Scan(&privileged)
	return privileged, err
}
